<?php $value=function($key)use($source){return htmlspecialchars($source&&isset($source->$key)?(string)$source->$key:'',ENT_QUOTES,'UTF-8');}; ?>
<div class="row">
    <div class="col-md-4 form-group"><label>Source type</label><select class="form-control" name="source_type"><?php foreach(array('pdf'=>'PDF','csv'=>'CSV','url'=>'URL','manual'=>'Manual entry','supplier_confirmation'=>'Supplier confirmation','approved_staff_reply'=>'Approved staff reply') as $key=>$label) { ?><option value="<?php echo $key; ?>" <?php echo $source&&$source->SourceType===$key?'selected':''; ?>><?php echo $label; ?></option><?php } ?></select></div>
    <div class="col-md-8 form-group"><label>Title</label><input class="form-control" name="title" required maxlength="255" value="<?php echo $value('Title'); ?>" placeholder="Official room policy / supplier confirmation reference"></div>

    <div class="col-md-8 form-group"><label>Official URL (required for URL sources)</label><input type="url" class="form-control" name="source_url" maxlength="2048" value="<?php echo $value('SourceUrl'); ?>" placeholder="https://..."></div>
    <div class="col-md-4 form-group"><label>Topic</label><input class="form-control" name="topic" required maxlength="80" pattern="[a-z][a-z0-9_]*" value="<?php echo $value('Topic'); ?>" placeholder="extra_bed"></div>
    <div class="col-md-4 form-group"><label>Package</label><select class="form-control selectpicker" data-live-search="true" name="product_id"><option value="0">No package restriction</option><?php foreach($products as $p) { ?><option value="<?php echo (int)$p->ProductID; ?>" <?php echo $source&&(int)$source->ProductID===(int)$p->ProductID?'selected':''; ?>><?php echo htmlspecialchars($p->Name,ENT_QUOTES,'UTF-8'); ?></option><?php } ?></select></div>
    <div class="col-md-4 form-group"><label>Resort</label><input class="form-control" name="resort_name" maxlength="255" value="<?php echo $value('ResortName'); ?>"></div>
    <div class="col-md-4 form-group"><label>Room type</label><input class="form-control" name="room_type" maxlength="255" value="<?php echo $value('RoomType'); ?>"></div>
    <?php foreach(array('ValidFrom'=>'valid_from','ValidTo'=>'valid_to','ReviewDue'=>'review_due') as $key=>$field) { ?><div class="col-md-4 form-group"><label><?php echo array('ValidFrom'=>'Valid from','ValidTo'=>'Valid until','ReviewDue'=>'Review due')[$key]; ?></label><input type="date" class="form-control" name="<?php echo $field; ?>" value="<?php echo $value($key); ?>"></div><?php } ?>
    <div class="col-12 form-group"><label>Approved excerpt / exact supplier wording</label><textarea class="form-control" name="excerpt" rows="5" maxlength="60000" placeholder="Paste only explicit policy wording. Leave unknown facts out."><?php echo $value('Excerpt'); ?></textarea><small class="form-text text-muted">Supplier confirmations and staff replies must retain a traceable sender/date/reference in the title or URL. The approved excerpt is the customer-facing answer wording.</small></div>
    <div class="col-12 form-group"><label class="checkbox"><input type="checkbox" name="all_rooms" value="1" <?php echo $source&&$source->AppliesToAllRooms?'checked':''; ?>><span class="mr-2"></span>The official excerpt explicitly applies to all room types in this resort/package.</label><small class="form-text text-muted">Required for a broader extra-bed source to apply to a named room. Agency-wide sources cannot establish a resort policy.</small></div>
</div>
